set -e
true
true
/usr/libexec/spades/spades-hammer /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/corrected/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/compress_all.py --input_file /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/corrected/corrected.yaml --ext_python_modules_home /usr/share/spades --max_threads 16 --output_dir /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/corrected --gzip_output
true
true
/usr/libexec/spades/spades-core /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K21/configs/config.info
/usr/libexec/spades/spades-core /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K33/configs/config.info
/usr/libexec/spades/spades-core /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/configs/config.info
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/copy_files.py /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/before_rr.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/before_rr.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/assembly_graph_after_simplification.gfa /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/assembly_graph_after_simplification.gfa /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/final_contigs.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/contigs.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/first_pe_contigs.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/first_pe_contigs.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/strain_graph.gfa /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/strain_graph.gfa /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/scaffolds.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/scaffolds.fasta /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/scaffolds.paths /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/scaffolds.paths /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/assembly_graph_with_scaffolds.gfa /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/assembly_graph_with_scaffolds.gfa /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/assembly_graph.fastg /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/assembly_graph.fastg /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/K55/final_contigs.paths /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/contigs.paths
true
/usr/bin/python3 /usr/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/scaffolds.fasta --misc_dir /gpfs01/home/jc428818/Placement/uce-tutorial/assemblies/anolis/misc --threshold_for_breaking_scaffolds 3
true
